steps:
  - name: 'devops-repository'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/c/app-devops-image:$COMMIT_SHA',
      '.'
    ]
  - name: 'devops-repository'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/devops-repository/app-devops-image:$COMMIT_SHA'
    ]
  - name: 'cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'devops-app-production',
      '--image',
      'us-central1-docker.pkg.dev/$PROJECT_ID/devops-repository/app-devops-image:$COMMIT_SHA',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated'
    ]
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/devops-repository/app-devops-image:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY